blank_issues_enabled: false
contact_links:
  - name: 💬 Questions & Support
    url: https://github.com/ShirshenduR/Streamify/discussions
    about: Please ask questions in GitHub Discussions instead of issues.

